name: workflow.yml
on:
  push:
    branches:
      - master
      - main
      - samver-implementation

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Application Version
        id: semvar-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'true'
          tag_prefix: ""
      - name: Generated Version
        run: echo "Version is ${{ steps.semvar-app.outputs.version }}"