name: workflow.yml
on:
  push:
    branches:
      - master
      - main
      - samver-implementation

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Application Version
        id: semvar-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'true'
          tag_prefix: ""

      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ steps.semvar-app.outputs.version }} \
            -f Dockerfile \
            .
          docker push ghcr.io/${{ github.repository }}-webapi_hestia --all-tags

      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semvar-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container images:
              - ghcr.io/${{ github.repository }}:-webapi_hestia${{ steps.semvar-app.outputs.version }}
          allowUpdates: true
          token: ${{ secrets.GHCR_TOKEN }}