name: workflow.yml
on:
  push:
    branches:
      - master
      - main
      - samver-implementation

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: semvar-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'true'
          tag_prefix: ""

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.version }}
          docker build -t $IMAGE_TAG -f Dockerfile .
          docker push $IMAGE_TAG

      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semvar-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container images:
            - ghcr.io/${{ github.repository }}:${{ steps.semvar-app.outputs.version }}
          allowUpdates: true
          token: ${{ secrets.GHCR_TOKEN }}


