name: workflow.yml
on:
  push:
    branches:
      - master
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Generate Semantic Version.
        id: semvar
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: 'true'
          tag_prefix: "v"  # Expecting tags like v1.2.3
          branch: "HEAD"
          version_format: "${major}.${minor}.${patch}"  # Ensures versioning follows semantic versioning

      - name: login to GHCR.
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image.
        run: |
          VERSION=${{ steps.semvar.outputs.version }}
          if [ -z "$VERSION" ]; then
            echo "Error: Version is empty."
            exit 1
          fi
          IMAGE_TAG=ghcr.io/${{ github.repository }}:$VERSION
          docker build -t $IMAGE_TAG -f Dockerfile .
          docker push $IMAGE_TAG

      - name: Create release notes.
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semvar.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container images:
            - ghcr.io/${{ github.repository }}:${{ steps.semvar.outputs.version }}
          allowUpdates: true
          token: ${{ secrets.GHCR_TOKEN }}
